### ISSUE TITLE
sockjs.js?9be2:1606 GET https://localhost/sockjs-node/info?t=1579773805212 net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by marcoippolito** [davellanedam/vue-skeleton-mvp#225]
Hi Daniel,
thanks for sharing your excellent mvp.

I'm having this error: "sockjs.js?9be2:1606 GET https://localhost/sockjs-node/info?t=1579773805212 net::ERR_CONNECTION_REFUSED"
what should I modify in order to solve it? 
![sockejsError01](https://user-images.githubusercontent.com/3073209/72980315-a80fe400-3dda-11ea-83cc-b254ba8e5dbf.jpg)

I added the local address in vue.config.js, but still got the problem:

    module.exports = {
      productionSourceMap: false,
      pluginOptions: {
        i18n: {
          enableInSFC: true
        }
      },
      devServer: {
       host: '192.168.1.7'
      }
    }

Marco

**Comment by davellanedam** [comment]
Hi Marco, were you able to solve it?
