### ISSUE TITLE
Why not using vuetify 2?

### ISSUE THREAD

**Issue by bagaskarala** [davellanedam/vue-skeleton-mvp#226]
As i mention i title, Why not using vuetify 2?

**Comment by davellanedam** [comment]
Because this was built when v2 was not yet released. And they changed many things that basically break everything. It will take probably a couple of days to fix this. I can’t do it now, don’t have much free time. If you want to help I would appreciate it.

**Comment by markim** [comment]
I can probably help on this. The biggest thing that needs updating is the vue validator.

I was able to get this working on my local machine. I also added a light / dark theme switch within vuetify 2. I will try my best to get to this soon!

**Comment by davellanedam** [comment]
That would be awesome mate! I appreciate it!

**Comment by davellanedam** [comment]
https://github.com/davellanedam/vue-skeleton-mvp/pull/229

**Comment by bagaskarala** [comment]
nice work dude 😎 thanks
