### ISSUE TITLE
example.spec.js in tests refers to a non-existent component HelloWorld.vue

### ISSUE THREAD

**Issue by itsMagondu** [davellanedam/vue-skeleton-mvp#238]
**Describe the bug**
HelloWorld.vue is referred to in tests but it does not exist. This causes tests to fail

**To Reproduce**
Run `npm test:unit` or `yarn test:unit`

**Expected behavior**
The test should pass

**Screenshots**

**Smartphone (please complete the following information):**

- OS:  macOS
- Version Catalina

**Comment by davellanedam** [comment]
I'm sorry about this @itsMagondu There's no unit tests in the project, file is removed now. Thank you!
