### ISSUE TITLE
Implementing use of namespacing with Vuex.

### ISSUE THREAD

**Issue by Ryuuji14** [davellanedam/vue-skeleton-mvp#241]
Hi, first off, I've got to say that this project is amazing! However I have a question, I was trying to implement in my project the part of loading, error, success. But I get this errors:

[vuex] unknown local mutation type: SHOW_LOADING, global type: users/SHOW_LOADING
[vuex] unknown local mutation type: SUCCESS, global type: users/SUCCESS
[vuex] unknown local mutation type: ERROR, global type: users/ERROR
[vuex] unknown local mutation type: SUCCESS, global type: users/SUCCESS

I think it's because of something with namespacing (because my module has it, while loading, error, and success don't) What can it be the approach to solve this? I read that I have to use something with '{root:true}", I tried to put it in every commit in the part of utils.js, and now I don't get the error, but it still doesn't show me the components, what do you think this could be?

**Comment by davellanedam** [comment]
Thank you! Remember to add it to mutations-type.js I think that’s what you are missing. Hope this helps, please let me know how it goes.

**Comment by Ryuuji14** [comment]
> Thank you! Remember to add it to mutations-type.js I think that’s what you are missing. Hope this helps, please let me know how it goes.

Sorry I didn't understand, what should I add there? I mean, there's SHOW_LOADING and the others already there. Or what did you mean?

**Comment by davellanedam** [comment]
I mean, it's not only to define the constant in their store file as a mutation, you will also need to add it to `mutation-types.js` file inside store folder.

**Comment by davellanedam** [comment]
Also you'll need to import `mutation-types.js` in the store file like this:

```
import * as types from '@/store/mutation-types';

const state = {};

const getters = {};

const actions = {};

const mutations = {};

export default {
  state,
  getters,
  actions,
  mutations
};

**Comment by Ryuuji14** [comment]
> Also you'll need to import `mutation-types.js` in the store file like this:
> 
> ```
> import * as types from '@/store/mutation-types';
> 
> const state = {
>   showLoading: true
> };
> 
> const getters = {
>   showLoading: (state) => state.showLoading
> };
> 
> const mutations = {
>   [types.SHOW_LOADING](state, value) {
>     state.showLoading = value;
>   }
> };
> 
> export default {
>   state,
>   getters,
>   mutations
> };
> ```

Yeah, I import exactly like that in my user module, the difference is that in the `export default` I include namespaced: true.

**Comment by Ryuuji14** [comment]
`export const buildSuccess = (
  msg,
  commit,
  resolve,
  resolveParam = undefined
) => {
  commit(types.SHOW_LOADING, false, { root: true })
  commit(types.SUCCESS, null, { root: true })
  setTimeout(() => {
    return msg
      ? commit(types.SUCCESS, msg, { root: true })
      : commit(types.SHOW_SUCCESS, false, { root: true })
  }, 0)
  commit(types.ERROR, null, { root: true })
  resolve(resolveParam)
}`
I edited your method and added the { root: true }, and now it doesn't show me the error but still the component doesn't appear, maybe I had to do something else?

**Comment by davellanedam** [comment]
To be honest without seeing your code is really hard to tell what’s going on.

**Comment by davellanedam** [comment]
This might help you.

https://vuex.vuejs.org/guide/modules.html

**Comment by Ryuuji14** [comment]
Thanks! I found out just now the problem, I did put the `{ root: true }` on the method that I said (and on handleError too), but the main problem after that wass that I didn't put the labels of ErrorMessage and SuccessMessage on my component. Now it works! Should I close the issue?

**Comment by Ryuuji14** [comment]
I have another question, how do you handle the ErrorMessage for the login? I mean, I only see the label, but I don't see that you do something on the auth.js to show the error if it can't login, and even, how do you do to show different errors? I mean, I only see the `en.json` where I see the messages but I can't find the place where you do a function to show different errors depending on the case (at least for the login).

**Comment by davellanedam** [comment]
Ok, that should come from the API, which is the responsible for those type of errors, (backend):

https://github.com/davellanedam/node-express-mongodb-jwt-rest-api-skeleton/blob/742dc979320848f2c291b1b4e92a56c5b2fe30ca/app/controllers/profile.js

And yeah, if this is solved we can close it, thanks!

**Comment by Ryuuji14** [comment]
Thanks! I'll check that out, if I have any other question, I might ask again hahaha. I'll close the issue.
