### ISSUE TITLE
Why do I need python to install all the dependencies?

### ISSUE THREAD

**Issue by kamalhm** [davellanedam/vue-skeleton-mvp#3]
Downloaded the repo, extract, cd into the project, and i ran

```npm install```

struck with this error 

```gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.```

**Comment by davellanedam** [comment]
Python is not required for that, it should be an issue with your npm installation, I guess you are using Windows. This may help you: https://catalin.me/how-to-fix-node-js-gyp-err-cant-find-python-executable-python-on-windows/
